apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriram-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sriram-springboot
  template:
    metadata:
      labels:
        app: sriram-springboot
    spec:
      containers:
        - name: springboot
          image: srirammani/sriram369:mani-ram
          ports: 
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: sriram-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sriram-springboot
